bind 0.0.0.0
protected-mode yes
port 6379

appendonly yes
appendfsync everysec
aof-use-rdb-preamble yes
save 900 1
save 300 10
save 60 10000

maxmemory-policy noeviction
tcp-keepalive 300
timeout 0
loglevel notice
dir /data
